<a href="https://colab.research.google.com/github/rockyroshanbehera/talentprofile-recommendation-system/blob/main/talentprofile.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install -q kaggle

In [ ]:
import os

os.environ["KAGGLE_API_TOKEN"] = "KGAT_b6038a88848c3adccdb821cb0f3383fd"

In [ ]:
!kaggle datasets download -d arshkon/linkedin-job-postings

Warning: Looks like you're using an outdated `kaggle` version (installed: 2.0.2), please consider upgrading to the latest version (2.2.2)
Dataset URL: https://www.kaggle.com/datasets/arshkon/linkedin-job-postings
License(s): CC-BY-SA-4.0
Downloading linkedin-job-postings.zip to /content
100% 159M/159M [00:11<00:00, 14.9MB/s]

In [ ]:
!unzip linkedin-job-postings.zip

Archive:  linkedin-job-postings.zip
  inflating: companies/companies.csv
  inflating: companies/company_industries.csv
  inflating: companies/company_specialities.csv
  inflating: companies/employee_counts.csv
  inflating: jobs/benefits.csv
  inflating: jobs/job_industries.csv
  inflating: jobs/job_skills.csv
  inflating: jobs/salaries.csv
  inflating: mappings/industries.csv
  inflating: mappings/skills.csv
  inflating: postings.csv

In [ ]:
import os

files = sorted(os.listdir("/content"))
print(files)

['.config', 'companies', 'jobs', 'linkedin-job-postings.zip', 'mappings', 'postings.csv', 'sample_data']

In [ ]:
import pandas as pd

postings = pd.read_csv("/content/postings.csv", engine='python', on_bad_lines='skip')
companies = pd.read_csv("/content/companies/companies.csv")
job_skills = pd.read_csv("/content/jobs/job_skills.csv")
job_industries = pd.read_csv("/content/jobs/job_industries.csv")
company_industries = pd.read_csv("/content/companies/company_industries.csv")
company_specialities = pd.read_csv("/content/companies/company_specialities.csv")
employee_counts = pd.read_csv("/content/companies/employee_counts.csv")
industries = pd.read_csv("/content/mappings/industries.csv")
benefits = pd.read_csv("/content/jobs/benefits.csv")
salaries = pd.read_csv("/content/jobs/salaries.csv")
skills = pd.read_csv("/content/mappings/skills.csv")

print("✅ All datasets loaded successfully!")

✅ All datasets loaded successfully!

In [ ]:
datasets = {
    "postings": postings,
    "companies": companies,
    "job_skills": job_skills,
    "job_industries": job_industries,
    "company_industries": company_industries,
    "company_specialities": company_specialities,
    "employee_counts": employee_counts,
    "industries": industries,
    "benefits": benefits,
    "salaries": salaries,
    "skills": skills
}

summary = pd.DataFrame({
    "Dataset": datasets.keys(),
    "Rows": [df.shape[0] for df in datasets.values()],
    "Columns": [df.shape[1] for df in datasets.values()]
})

summary

                 Dataset    Rows  Columns
0               postings  123849       31
1              companies   24473       10
2             job_skills  213768        2
3         job_industries  164808        2
4     company_industries   24375        2
5   company_specialities  169387        2
6        employee_counts   35787        4
7             industries     422        2
8               benefits   67943        3
9               salaries   40785        8
10                skills      35        2

In [ ]:

def inspect_dataset(df, name):
    print("=" * 80)
    print(f"DATASET : {name}")
    print("=" * 80)

    print(f"\nShape : {df.shape}")

    print("\nColumn Names")
    print(df.columns.tolist())

    print("\nData Types")
    print(df.dtypes)

    print("\nMissing Values")
    print(df.isnull().sum())

    print("\nDuplicate Rows")
    print(df.duplicated().sum())

    print("\nFirst Five Rows")
    display(df.head())

In [ ]:
inspect_dataset(postings, "Postings")

================================================================================
DATASET : Postings
================================================================================

Shape : (123849, 31)

Column Names
['job_id', 'company_name', 'title', 'description', 'max_salary', 'pay_period', 'location', 'company_id', 'views', 'med_salary', 'min_salary', 'formatted_work_type', 'applies', 'original_listed_time', 'remote_allowed', 'job_posting_url', 'application_url', 'application_type', 'expiry', 'closed_time', 'formatted_experience_level', 'skills_desc', 'listed_time', 'posting_domain', 'sponsored', 'work_type', 'currency', 'compensation_type', 'normalized_salary', 'zip_code', 'fips']

Data Types
job_id                          int64
company_name                   object
title                          object
description                    object
max_salary                    float64
pay_period                     object
location                       object
company_id                    float64
views                         float64
med_salary                    float64
min_salary                    float64
formatted_work_type            object
applies                       float64
original_listed_time          float64
remote_allowed                float64
job_posting_url                object
application_url                object
application_type               object
expiry                        float64
closed_time                   float64
formatted_experience_level     object
skills_desc                    object
listed_time                   float64
posting_domain                 object
sponsored                       int64
work_type                      object
currency                       object
compensation_type              object
normalized_salary             float64
zip_code                      float64
fips                          float64
dtype: object

Missing Values
job_id                             0
company_name                    1719
title                              0
description                        7
max_salary                     94056
pay_period                     87776
location                           0
company_id                      1717
views                           1689
med_salary                    117569
min_salary                     94056
formatted_work_type                0
applies                       100529
original_listed_time               0
remote_allowed                108603
job_posting_url                    0
application_url                36665
application_type                   0
expiry                             0
closed_time                   122776
formatted_experience_level     29409
skills_desc                   121410
listed_time                        0
posting_domain                 39968
sponsored                          0
work_type                          0
currency                       87776
compensation_type              87776
normalized_salary              87776
zip_code                       20872
fips                           27415
dtype: int64

Duplicate Rows
0

First Five Rows

,job_id,company_name,title,description,max_salary,pay_period,location,company_id,views,med_salary,...,skills_desc,listed_time,posting_domain,sponsored,work_type,currency,compensation_type,normalized_salary,zip_code,fips
0,921716,Corcoran Sawyer Smith,Marketing Coordinator,Job descriptionA leading real estate firm in N...,20.0,HOURLY,"Princeton, NJ",2774458.0,20.0,NaN,...,Requirements: \n\nWe are seeking a College or ...,1.713398e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,38480.0,8540.0,34021.0
1,1829192,NaN,Mental Health Therapist/Counselor,"At Aspen Therapy and Wellness , we are committ...",50.0,HOURLY,"Fort Collins, CO",NaN,1.0,NaN,...,NaN,1.712858e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,83200.0,80521.0,8069.0
2,10998357,The National Exemplar,Assitant Restaurant Manager,The National Exemplar is accepting application...,65000.0,YEARLY,"Cincinnati, OH",64896719.0,8.0,NaN,...,We are currently accepting resumes for FOH - A...,1.713278e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,55000.0,45202.0,39061.0
3,23221523,"Abrams Fensterman, LLP",Senior Elder Law / Trusts and Estates Associat...,Senior Associate Attorney - Elder Law / Trusts...,175000.0,YEARLY,"New Hyde Park, NY",766262.0,16.0,NaN,...,This position requires a baseline understandin...,1.712896e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,157500.0,11040.0,36059.0
4,35982263,NaN,Service Technician,Looking for HVAC service tech with experience ...,80000.0,YEARLY,"Burlington, IA",NaN,3.0,NaN,...,NaN,1.713452e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,70000.0,52601.0,19057.0

In [ ]:
inspect_dataset(companies, "Companies")

================================================================================
DATASET : Companies
================================================================================

Shape : (24473, 10)

Column Names
['company_id', 'name', 'description', 'company_size', 'state', 'country', 'city', 'zip_code', 'address', 'url']

Data Types
company_id        int64
name             object
description      object
company_size    float64
state            object
country          object
city             object
zip_code         object
address          object
url              object
dtype: object

Missing Values
company_id         0
name               1
description      297
company_size    2774
state             22
country            0
city               1
zip_code          28
address           22
url                0
dtype: int64

Duplicate Rows
0

First Five Rows

,company_id,name,description,company_size,state,country,city,zip_code,address,url
0,1009,IBM,"At IBM, we do more than work. We create. We cr...",7.0,NY,US,"Armonk, New York",10504,International Business Machines Corp.,https://www.linkedin.com/company/ibm
1,1016,GE HealthCare,Every day millions of people feel the impact o...,7.0,0,US,Chicago,0,-,https://www.linkedin.com/company/gehealthcare
2,1025,Hewlett Packard Enterprise,Official LinkedIn of Hewlett Packard Enterpris...,7.0,Texas,US,Houston,77389,1701 E Mossy Oaks Rd Spring,https://www.linkedin.com/company/hewlett-packa...
3,1028,Oracle,We’re a cloud technology company that provides...,7.0,Texas,US,Austin,78741,2300 Oracle Way,https://www.linkedin.com/company/oracle
4,1033,Accenture,Accenture is a leading global professional ser...,7.0,0,IE,Dublin 2,0,Grand Canal Harbour,https://www.linkedin.com/company/accenture

In [ ]:
inspect_dataset(job_skills, "Job Skills")

================================================================================
DATASET : Job Skills
================================================================================

Shape : (213768, 2)

Column Names
['job_id', 'skill_abr']

Data Types
job_id        int64
skill_abr    object
dtype: object

Missing Values
job_id       0
skill_abr    0
dtype: int64

Duplicate Rows
0

First Five Rows

       job_id skill_abr
0  3884428798      MRKT
1  3884428798        PR
2  3884428798       WRT
3  3887473071      SALE
4  3887465684       FIN

In [ ]:
inspect_dataset(job_industries, "Job Industries")

================================================================================
DATASET : Job Industries
================================================================================

Shape : (164808, 2)

Column Names
['job_id', 'industry_id']

Data Types
job_id         int64
industry_id    int64
dtype: object

Missing Values
job_id         0
industry_id    0
dtype: int64

Duplicate Rows
0

First Five Rows

       job_id  industry_id
0  3884428798           82
1  3887473071           48
2  3887465684           41
3  3887467939           82
4  3887467939           80

In [ ]:
inspect_dataset(industries, "Industries")

================================================================================
DATASET : Industries
================================================================================

Shape : (422, 2)

Column Names
['industry_id', 'industry_name']

Data Types
industry_id       int64
industry_name    object
dtype: object

Missing Values
industry_id       0
industry_name    34
dtype: int64

Duplicate Rows
0

First Five Rows

   industry_id                         industry_name
0            1       Defense and Space Manufacturing
1            3       Computer Hardware Manufacturing
2            4                  Software Development
3            5          Computer Networking Products
4            6  Technology, Information and Internet

In [ ]:
inspect_dataset(industries, "Industries")

================================================================================
DATASET : Industries
================================================================================

Shape : (422, 2)

Column Names
['industry_id', 'industry_name']

Data Types
industry_id       int64
industry_name    object
dtype: object

Missing Values
industry_id       0
industry_name    34
dtype: int64

Duplicate Rows
0

First Five Rows

   industry_id                         industry_name
0            1       Defense and Space Manufacturing
1            3       Computer Hardware Manufacturing
2            4                  Software Development
3            5          Computer Networking Products
4            6  Technology, Information and Internet

In [ ]:
inspect_dataset(skills, "Skills")

================================================================================
DATASET : Skills
================================================================================

Shape : (35, 2)

Column Names
['skill_abr', 'skill_name']

Data Types
skill_abr     object
skill_name    object
dtype: object

Missing Values
skill_abr     0
skill_name    0
dtype: int64

Duplicate Rows
0

First Five Rows

  skill_abr          skill_name
0       ART        Art/Creative
1      DSGN              Design
2      ADVR         Advertising
3      PRDM  Product Management
4      DIST        Distribution

In [ ]:
for name, df in {
    "postings": postings,
    "companies": companies,
    "job_skills": job_skills,
    "job_industries": job_industries,
    "industries": industries,
    "skills": skills
}.items():

    print("="*60)
    print(name)
    print("="*60)
    print(df.columns.tolist())

============================================================
postings
============================================================
['job_id', 'company_name', 'title', 'description', 'max_salary', 'pay_period', 'location', 'company_id', 'views', 'med_salary', 'min_salary', 'formatted_work_type', 'applies', 'original_listed_time', 'remote_allowed', 'job_posting_url', 'application_url', 'application_type', 'expiry', 'closed_time', 'formatted_experience_level', 'skills_desc', 'listed_time', 'posting_domain', 'sponsored', 'work_type', 'currency', 'compensation_type', 'normalized_salary', 'zip_code', 'fips']
============================================================
companies
============================================================
['company_id', 'name', 'description', 'company_size', 'state', 'country', 'city', 'zip_code', 'address', 'url']
============================================================
job_skills
============================================================
['job_id', 'skill_abr']
============================================================
job_industries
============================================================
['job_id', 'industry_id']
============================================================
industries
============================================================
['industry_id', 'industry_name']
============================================================
skills
============================================================
['skill_abr', 'skill_name']

In [ ]:
postings.describe(include='all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
job_id,123849.0,NaN,NaN,NaN,3896402138.074615,84043545.161881,921716.0,3894586595.0,3901998406.0,3904707077.0,3906267224.0
company_name,122130,24428,Liberty Healthcare and Rehabilitation Services,1108,NaN,NaN,NaN,NaN,NaN,NaN,NaN
title,123849,72521,Sales Manager,673,NaN,NaN,NaN,NaN,NaN,NaN,NaN
description,123842,107827,Position Summary: Our Sales Manager has managi...,474,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max_salary,29793.0,NaN,NaN,NaN,91939.423461,701110.138622,1.0,48.28,80000.0,140000.0,120000000.0
pay_period,36073,5,YEARLY,20628,NaN,NaN,NaN,NaN,NaN,NaN,NaN
location,123849,8526,United States,8125,NaN,NaN,NaN,NaN,NaN,NaN,NaN
company_id,122132.0,NaN,NaN,NaN,12204012.335015,25541431.65742,1009.0,14352.0,226965.0,8047188.0,103472979.0
views,122160.0,NaN,NaN,NaN,14.618247,85.903598,1.0,3.0,4.0,8.0,9975.0
med_salary,6280.0,NaN,NaN,NaN,22015.619876,52255.873846,0.0,18.94,25.5,2510.5,750000.0
min_salary,29793.0,NaN,NaN,NaN,64910.847434,495973.793504,1.0,37.0,60000.0,100000.0,85000000.0
formatted_work_type,123849,7,Full-time,98814,NaN,NaN,NaN,NaN,NaN,NaN,NaN
applies,23320.0,NaN,NaN,NaN,10.591981,29.047395,1.0,1.0,3.0,8.0,967.0
original_listed_time,123849.0,NaN,NaN,NaN,1713152338799.941406,484820878.414716,1701810533000.0,1712862876000.0,1713395039000.0,1713478324000.0,1713572803000.0
remote_allowed,15246.0,NaN,NaN,NaN,1.0,0.0,1.0,1.0,1.0,1.0,1.0
job_posting_url,123849,123849,https://www.linkedin.com/jobs/view/3906267224/...,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
application_url,87184,84800,https://app.dataannotation.tech/worker_signup?...,205,NaN,NaN,NaN,NaN,NaN,NaN,NaN
application_type,123849,4,OffsiteApply,84607,NaN,NaN,NaN,NaN,NaN,NaN,NaN
expiry,123849.0,NaN,NaN,NaN,1716213036608.151855,2321393898.084225,1712903448000.0,1715480718000.0,1716042264000.0,1716088229000.0,1729124796000.0
closed_time,1073.0,NaN,NaN,NaN,1712927892086.672852,362289347.409251,1712345932000.0,1712669760000.0,1712669910000.0,1713282569000.0,1713562107000.0
formatted_experience_level,94440,6,Mid-Senior level,41489,NaN,NaN,NaN,NaN,NaN,NaN,NaN
skills_desc,2439,2212,This position requires the following skills: E...,28,NaN,NaN,NaN,NaN,NaN,NaN,NaN
listed_time,123849.0,NaN,NaN,NaN,1713204445996.681396,398912198.594052,1711317014000.0,1712885544000.0,1713407593000.0,1713483628000.0,1713572816000.0
posting_domain,83881,4443,www.click2apply.net,3811,NaN,NaN,NaN,NaN,NaN,NaN,NaN
sponsored,123849.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
work_type,123849,7,FULL_TIME,98814,NaN,NaN,NaN,NaN,NaN,NaN,NaN
currency,36073,6,USD,36058,NaN,NaN,NaN,NaN,NaN,NaN,NaN
compensation_type,36073,1,BASE_SALARY,36073,NaN,NaN,NaN,NaN,NaN,NaN,NaN
normalized_salary,36073.0,NaN,NaN,NaN,205327.03685,5097626.762136,0.0,52000.0,81500.0,125000.0,535600000.0
zip_code,102977.0,NaN,NaN,NaN,50400.491887,30252.232515,1001.0,24112.0,48059.0,78201.0,99901.0
fips,96434.0,NaN,NaN,NaN,28713.879887,16015.929825,1003.0,13121.0,29183.0,42077.0,56045.0

In [ ]:
companies.describe(include='all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
company_id,24473.0,NaN,NaN,NaN,20522391.62191,31659289.154874,1009.0,165404.0,2738154.0,26241420.0,103472979.0
name,24472,24428,Confidential,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
description,24176,24164,.,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
company_size,21699.0,NaN,NaN,NaN,3.349233,1.904503,1.0,2.0,3.0,5.0,7.0
state,24451,788,0,2175,NaN,NaN,NaN,NaN,NaN,NaN,NaN
country,24473,81,US,21635,NaN,NaN,NaN,NaN,NaN,NaN,NaN
city,24472,4124,New York,1185,NaN,NaN,NaN,NaN,NaN,NaN,NaN
zip_code,24445,7779,0,3060,NaN,NaN,NaN,NaN,NaN,NaN,NaN
address,24451,19476,0,3972,NaN,NaN,NaN,NaN,NaN,NaN,NaN
url,24473,24473,https://www.linkedin.com/company/blackve,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
missing = postings.isnull().sum().sort_values(ascending=False)

missing = missing[missing > 0]

missing

closed_time                   122776
skills_desc                   121410
med_salary                    117569
remote_allowed                108603
applies                       100529
min_salary                     94056
max_salary                     94056
currency                       87776
compensation_type              87776
pay_period                     87776
normalized_salary              87776
posting_domain                 39968
application_url                36665
formatted_experience_level     29409
fips                           27415
zip_code                       20872
company_name                    1719
company_id                      1717
views                           1689
description                        7
dtype: int64

In [ ]:
print("Postings :", postings.duplicated().sum())

print("Companies :", companies.duplicated().sum())

print("Job Skills :", job_skills.duplicated().sum())

Postings : 0
Companies : 0
Job Skills : 0

## Business Understanding

Goal:

Develop an AI-powered Universal Freelancer Recommendation System.

The dataset contains LinkedIn job postings and related metadata.

The recommendation system will transform job information into searchable freelancer-like profiles.

The final system will recommend the best matching professionals based on natural language requirements using NLP.

Key datasets:

- postings → job information
- companies → company details
- job_skills → required skills
- industries → industry names

In [ ]:
postings.columns.tolist()

['job_id',
 'company_name',
 'title',
 'description',
 'max_salary',
 'pay_period',
 'location',
 'company_id',
 'views',
 'med_salary',
 'min_salary',
 'formatted_work_type',
 'applies',
 'original_listed_time',
 'remote_allowed',
 'job_posting_url',
 'application_url',
 'application_type',
 'expiry',
 'closed_time',
 'formatted_experience_level',
 'skills_desc',
 'listed_time',
 'posting_domain',
 'sponsored',
 'work_type',
 'currency',
 'compensation_type',
 'normalized_salary',
 'zip_code',
 'fips']

In [ ]:
companies.columns.tolist()

['company_id',
 'name',
 'description',
 'company_size',
 'state',
 'country',
 'city',
 'zip_code',
 'address',
 'url']

In [ ]:
job_skills.columns.tolist()

['job_id', 'skill_abr']

In [ ]:
job_industries.columns.tolist()

['job_id', 'industry_id']

In [ ]:
industries.columns.tolist()

['industry_id', 'industry_name']

In [ ]:
skills.columns.tolist()

['skill_abr', 'skill_name']

In [ ]:
postings.columns.tolist()

['job_id',
 'company_name',
 'title',
 'description',
 'max_salary',
 'pay_period',
 'location',
 'company_id',
 'views',
 'med_salary',
 'min_salary',
 'formatted_work_type',
 'applies',
 'original_listed_time',
 'remote_allowed',
 'job_posting_url',
 'application_url',
 'application_type',
 'expiry',
 'closed_time',
 'formatted_experience_level',
 'skills_desc',
 'listed_time',
 'posting_domain',
 'sponsored',
 'work_type',
 'currency',
 'compensation_type',
 'normalized_salary',
 'zip_code',
 'fips']

In [ ]:
postings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 123849 entries, 0 to 123848
Data columns (total 31 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   job_id                      123849 non-null  int64
 1   company_name                122130 non-null  object
 2   title                       123849 non-null  object
 3   description                 123842 non-null  object
 4   max_salary                  29793 non-null   float64
 5   pay_period                  36073 non-null   object
 6   location                    123849 non-null  object
 7   company_id                  122132 non-null  float64
 8   views                       122160 non-null  float64
 9   med_salary                  6280 non-null    float64
 10  min_salary                  29793 non-null   float64
 11  formatted_work_type         123849 non-null  object
 12  applies                     23320 non-null   float64
 13  original_listed_time        123849 non-null  float64
 14  remote_allowed              15246 non-null   float64
 15  job_posting_url             123849 non-null  object
 16  application_url             87184 non-null   object
 17  application_type            123849 non-null  object
 18  expiry                      123849 non-null  float64
 19  closed_time                 1073 non-null    float64
 20  formatted_experience_level  94440 non-null   object
 21  skills_desc                 2439 non-null    object
 22  listed_time                 123849 non-null  float64
 23  posting_domain              83881 non-null   object
 24  sponsored                   123849 non-null  int64
 25  work_type                   123849 non-null  object
 26  currency                    36073 non-null   object
 27  compensation_type           36073 non-null   object
 28  normalized_salary           36073 non-null   float64
 29  zip_code                    102977 non-null  float64
 30  fips                        96434 non-null   float64
dtypes: float64(14), int64(2), object(15)
memory usage: 29.3+ MB

In [ ]:
missing = (
    postings.isnull()
    .sum()
    .sort_values(ascending=False)
)

missing[missing > 0]

closed_time                   122776
skills_desc                   121410
med_salary                    117569
remote_allowed                108603
applies                       100529
min_salary                     94056
max_salary                     94056
currency                       87776
compensation_type              87776
pay_period                     87776
normalized_salary              87776
posting_domain                 39968
application_url                36665
formatted_experience_level     29409
fips                           27415
zip_code                       20872
company_name                    1719
company_id                      1717
views                           1689
description                        7
dtype: int64

In [ ]:
postings.head().T

,0,1,2,3,4
job_id,921716,1829192,10998357,23221523,35982263
company_name,Corcoran Sawyer Smith,NaN,The National Exemplar,"Abrams Fensterman, LLP",NaN
title,Marketing Coordinator,Mental Health Therapist/Counselor,Assitant Restaurant Manager,Senior Elder Law / Trusts and Estates Associat...,Service Technician
description,Job descriptionA leading real estate firm in N...,"At Aspen Therapy and Wellness , we are committ...",The National Exemplar is accepting application...,Senior Associate Attorney - Elder Law / Trusts...,Looking for HVAC service tech with experience ...
max_salary,20.0,50.0,65000.0,175000.0,80000.0
pay_period,HOURLY,HOURLY,YEARLY,YEARLY,YEARLY
location,"Princeton, NJ","Fort Collins, CO","Cincinnati, OH","New Hyde Park, NY","Burlington, IA"
company_id,2774458.0,NaN,64896719.0,766262.0,NaN
views,20.0,1.0,8.0,16.0,3.0
med_salary,NaN,NaN,NaN,NaN,NaN
min_salary,17.0,30.0,45000.0,140000.0,60000.0
formatted_work_type,Full-time,Full-time,Full-time,Full-time,Full-time
applies,2.0,NaN,NaN,NaN,NaN
original_listed_time,1713397508000.0,1712857887000.0,1713277614000.0,1712895812000.0,1713451943000.0
remote_allowed,NaN,NaN,NaN,NaN,NaN
job_posting_url,https://www.linkedin.com/jobs/view/921716/?trk...,https://www.linkedin.com/jobs/view/1829192/?tr...,https://www.linkedin.com/jobs/view/10998357/?t...,https://www.linkedin.com/jobs/view/23221523/?t...,https://www.linkedin.com/jobs/view/35982263/?t...
application_url,NaN,NaN,NaN,NaN,NaN
application_type,ComplexOnsiteApply,ComplexOnsiteApply,ComplexOnsiteApply,ComplexOnsiteApply,ComplexOnsiteApply
expiry,1715989508000.0,1715449887000.0,1715869614000.0,1715487812000.0,1716043943000.0
closed_time,NaN,NaN,NaN,NaN,NaN
formatted_experience_level,NaN,NaN,NaN,NaN,NaN
skills_desc,Requirements: \n\nWe are seeking a College or ...,NaN,We are currently accepting resumes for FOH - A...,This position requires a baseline understandin...,NaN
listed_time,1713397508000.0,1712857887000.0,1713277614000.0,1712895812000.0,1713451943000.0
posting_domain,NaN,NaN,NaN,NaN,NaN
sponsored,0,0,0,0,0
work_type,FULL_TIME,FULL_TIME,FULL_TIME,FULL_TIME,FULL_TIME
currency,USD,USD,USD,USD,USD
compensation_type,BASE_SALARY,BASE_SALARY,BASE_SALARY,BASE_SALARY,BASE_SALARY
normalized_salary,38480.0,83200.0,55000.0,157500.0,70000.0
zip_code,8540.0,80521.0,45202.0,11040.0,52601.0
fips,34021.0,8069.0,39061.0,36059.0,19057.0

In [ ]:
postings.columns.tolist()

['job_id',
 'company_name',
 'title',
 'description',
 'max_salary',
 'pay_period',
 'location',
 'company_id',
 'views',
 'med_salary',
 'min_salary',
 'formatted_work_type',
 'applies',
 'original_listed_time',
 'remote_allowed',
 'job_posting_url',
 'application_url',
 'application_type',
 'expiry',
 'closed_time',
 'formatted_experience_level',
 'skills_desc',
 'listed_time',
 'posting_domain',
 'sponsored',
 'work_type',
 'currency',
 'compensation_type',
 'normalized_salary',
 'zip_code',
 'fips']

In [ ]:

postings_clean = postings[[
    "job_id",
    "company_id",
    "company_name",
    "title",
    "description",
    "location",
    "formatted_work_type",
    "formatted_experience_level",
    "skills_desc"
]].copy()

postings_clean.head()

,job_id,company_id,company_name,title,description,location,formatted_work_type,formatted_experience_level,skills_desc
0,921716,2774458.0,Corcoran Sawyer Smith,Marketing Coordinator,Job descriptionA leading real estate firm in N...,"Princeton, NJ",Full-time,NaN,Requirements: \n\nWe are seeking a College or ...
1,1829192,NaN,NaN,Mental Health Therapist/Counselor,"At Aspen Therapy and Wellness , we are committ...","Fort Collins, CO",Full-time,NaN,NaN
2,10998357,64896719.0,The National Exemplar,Assitant Restaurant Manager,The National Exemplar is accepting application...,"Cincinnati, OH",Full-time,NaN,We are currently accepting resumes for FOH - A...
3,23221523,766262.0,"Abrams Fensterman, LLP",Senior Elder Law / Trusts and Estates Associat...,Senior Associate Attorney - Elder Law / Trusts...,"New Hyde Park, NY",Full-time,NaN,This position requires a baseline understandin...
4,35982263,NaN,NaN,Service Technician,Looking for HVAC service tech with experience ...,"Burlington, IA",Full-time,NaN,NaN

In [ ]:
postings_clean.isnull().sum().sort_values(ascending=False)

skills_desc                   121410
formatted_experience_level     29409
company_name                    1719
company_id                      1717
description                        7
job_id                             0
title                              0
formatted_work_type                0
location                           0
dtype: int64

In [ ]:
print("Duplicates Before:", postings_clean.duplicated().sum())

postings_clean.drop_duplicates(inplace=True)

print("Duplicates After:", postings_clean.duplicated().sum())

Duplicates Before: 0
Duplicates After: 0

In [ ]:
text_columns = [
    "title",
    "description",
    "location",
    "formatted_work_type",
    "formatted_experience_level",
    "skills_desc"
]

for col in text_columns:
    postings_clean[col] = postings_clean[col].fillna("")

In [ ]:
companies_clean = companies[[
    "company_id",
    "name",
    "description"
]].copy()

companies_clean.columns = [
    "company_id",
    "company_name_full",
    "company_description"
]

master_df = postings_clean.merge(
    companies_clean,
    on="company_id",
    how="left"
)

master_df.head()

,job_id,company_id,company_name,title,description,location,formatted_work_type,formatted_experience_level,skills_desc,company_name_full,company_description
0,921716,2774458.0,Corcoran Sawyer Smith,Marketing Coordinator,Job descriptionA leading real estate firm in N...,"Princeton, NJ",Full-time,,Requirements: \n\nWe are seeking a College or ...,Corcoran Sawyer Smith,With years of experience helping local buyers ...
1,1829192,NaN,NaN,Mental Health Therapist/Counselor,"At Aspen Therapy and Wellness , we are committ...","Fort Collins, CO",Full-time,,,NaN,NaN
2,10998357,64896719.0,The National Exemplar,Assitant Restaurant Manager,The National Exemplar is accepting application...,"Cincinnati, OH",Full-time,,We are currently accepting resumes for FOH - A...,The National Exemplar,"In April of 1983, The National Exemplar began ..."
3,23221523,766262.0,"Abrams Fensterman, LLP",Senior Elder Law / Trusts and Estates Associat...,Senior Associate Attorney - Elder Law / Trusts...,"New Hyde Park, NY",Full-time,,This position requires a baseline understandin...,"Abrams Fensterman, LLP","Abrams Fensterman, LLP is a full-service law f..."
4,35982263,NaN,NaN,Service Technician,Looking for HVAC service tech with experience ...,"Burlington, IA",Full-time,,,NaN,NaN

In [ ]:
master_df = master_df.merge(
    job_skills,
    on="job_id",
    how="left"
)

master_df = master_df.merge(
    skills,
    on="skill_abr",
    how="left"
)

master_df.head()

,job_id,company_id,company_name,title,description,location,formatted_work_type,formatted_experience_level,skills_desc,company_name_full,company_description,skill_abr,skill_name
0,921716,2774458.0,Corcoran Sawyer Smith,Marketing Coordinator,Job descriptionA leading real estate firm in N...,"Princeton, NJ",Full-time,,Requirements: \n\nWe are seeking a College or ...,Corcoran Sawyer Smith,With years of experience helping local buyers ...,MRKT,Marketing
1,921716,2774458.0,Corcoran Sawyer Smith,Marketing Coordinator,Job descriptionA leading real estate firm in N...,"Princeton, NJ",Full-time,,Requirements: \n\nWe are seeking a College or ...,Corcoran Sawyer Smith,With years of experience helping local buyers ...,SALE,Sales
2,1829192,NaN,NaN,Mental Health Therapist/Counselor,"At Aspen Therapy and Wellness , we are committ...","Fort Collins, CO",Full-time,,,NaN,NaN,HCPR,Health Care Provider
3,10998357,64896719.0,The National Exemplar,Assitant Restaurant Manager,The National Exemplar is accepting application...,"Cincinnati, OH",Full-time,,We are currently accepting resumes for FOH - A...,The National Exemplar,"In April of 1983, The National Exemplar began ...",MGMT,Management
4,10998357,64896719.0,The National Exemplar,Assitant Restaurant Manager,The National Exemplar is accepting application...,"Cincinnati, OH",Full-time,,We are currently accepting resumes for FOH - A...,The National Exemplar,"In April of 1983, The National Exemplar began ...",MNFC,Manufacturing

In [ ]:
master_df = master_df.merge(
    job_industries,
    on="job_id",
    how="left"
)

master_df = master_df.merge(
    industries,
    on="industry_id",
    how="left"
)

master_df.head()

,job_id,company_id,company_name,title,description,location,formatted_work_type,formatted_experience_level,skills_desc,company_name_full,company_description,skill_abr,skill_name,industry_id,industry_name
0,921716,2774458.0,Corcoran Sawyer Smith,Marketing Coordinator,Job descriptionA leading real estate firm in N...,"Princeton, NJ",Full-time,,Requirements: \n\nWe are seeking a College or ...,Corcoran Sawyer Smith,With years of experience helping local buyers ...,MRKT,Marketing,44.0,Real Estate
1,921716,2774458.0,Corcoran Sawyer Smith,Marketing Coordinator,Job descriptionA leading real estate firm in N...,"Princeton, NJ",Full-time,,Requirements: \n\nWe are seeking a College or ...,Corcoran Sawyer Smith,With years of experience helping local buyers ...,SALE,Sales,44.0,Real Estate
2,1829192,NaN,NaN,Mental Health Therapist/Counselor,"At Aspen Therapy and Wellness , we are committ...","Fort Collins, CO",Full-time,,,NaN,NaN,HCPR,Health Care Provider,NaN,NaN
3,10998357,64896719.0,The National Exemplar,Assitant Restaurant Manager,The National Exemplar is accepting application...,"Cincinnati, OH",Full-time,,We are currently accepting resumes for FOH - A...,The National Exemplar,"In April of 1983, The National Exemplar began ...",MGMT,Management,32.0,Restaurants
4,10998357,64896719.0,The National Exemplar,Assitant Restaurant Manager,The National Exemplar is accepting application...,"Cincinnati, OH",Full-time,,We are currently accepting resumes for FOH - A...,The National Exemplar,"In April of 1983, The National Exemplar began ...",MNFC,Manufacturing,32.0,Restaurants

In [ ]:
print(master_df.shape)

master_df.head()

(280665, 15)

,job_id,company_id,company_name,title,description,location,formatted_work_type,formatted_experience_level,skills_desc,company_name_full,company_description,skill_abr,skill_name,industry_id,industry_name
0,921716,2774458.0,Corcoran Sawyer Smith,Marketing Coordinator,Job descriptionA leading real estate firm in N...,"Princeton, NJ",Full-time,,Requirements: \n\nWe are seeking a College or ...,Corcoran Sawyer Smith,With years of experience helping local buyers ...,MRKT,Marketing,44.0,Real Estate
1,921716,2774458.0,Corcoran Sawyer Smith,Marketing Coordinator,Job descriptionA leading real estate firm in N...,"Princeton, NJ",Full-time,,Requirements: \n\nWe are seeking a College or ...,Corcoran Sawyer Smith,With years of experience helping local buyers ...,SALE,Sales,44.0,Real Estate
2,1829192,NaN,NaN,Mental Health Therapist/Counselor,"At Aspen Therapy and Wellness , we are committ...","Fort Collins, CO",Full-time,,,NaN,NaN,HCPR,Health Care Provider,NaN,NaN
3,10998357,64896719.0,The National Exemplar,Assitant Restaurant Manager,The National Exemplar is accepting application...,"Cincinnati, OH",Full-time,,We are currently accepting resumes for FOH - A...,The National Exemplar,"In April of 1983, The National Exemplar began ...",MGMT,Management,32.0,Restaurants
4,10998357,64896719.0,The National Exemplar,Assitant Restaurant Manager,The National Exemplar is accepting application...,"Cincinnati, OH",Full-time,,We are currently accepting resumes for FOH - A...,The National Exemplar,"In April of 1983, The National Exemplar began ...",MNFC,Manufacturing,32.0,Restaurants

In [ ]:
master_df.shape

(280665, 15)

In [ ]:
master_df.head()

,job_id,company_id,company_name,title,description,location,formatted_work_type,formatted_experience_level,skills_desc,company_name_full,company_description,skill_abr,skill_name,industry_id,industry_name
0,921716,2774458.0,Corcoran Sawyer Smith,Marketing Coordinator,Job descriptionA leading real estate firm in N...,"Princeton, NJ",Full-time,,Requirements: \n\nWe are seeking a College or ...,Corcoran Sawyer Smith,With years of experience helping local buyers ...,MRKT,Marketing,44.0,Real Estate
1,921716,2774458.0,Corcoran Sawyer Smith,Marketing Coordinator,Job descriptionA leading real estate firm in N...,"Princeton, NJ",Full-time,,Requirements: \n\nWe are seeking a College or ...,Corcoran Sawyer Smith,With years of experience helping local buyers ...,SALE,Sales,44.0,Real Estate
2,1829192,NaN,NaN,Mental Health Therapist/Counselor,"At Aspen Therapy and Wellness , we are committ...","Fort Collins, CO",Full-time,,,NaN,NaN,HCPR,Health Care Provider,NaN,NaN
3,10998357,64896719.0,The National Exemplar,Assitant Restaurant Manager,The National Exemplar is accepting application...,"Cincinnati, OH",Full-time,,We are currently accepting resumes for FOH - A...,The National Exemplar,"In April of 1983, The National Exemplar began ...",MGMT,Management,32.0,Restaurants
4,10998357,64896719.0,The National Exemplar,Assitant Restaurant Manager,The National Exemplar is accepting application...,"Cincinnati, OH",Full-time,,We are currently accepting resumes for FOH - A...,The National Exemplar,"In April of 1983, The National Exemplar began ...",MNFC,Manufacturing,32.0,Restaurants

In [ ]:
postings_clean.isnull().sum().sort_values(ascending=False)

company_name                  1719
company_id                    1717
job_id                           0
title                            0
description                      0
location                         0
formatted_work_type              0
formatted_experience_level       0
skills_desc                      0
dtype: int64

In [ ]:

skills_grouped = (
    master_df
    .groupby("job_id")["skill_name"]
    .apply(lambda x: ", ".join(sorted(set(x.dropna()))))
    .reset_index()
)

skills_grouped.head()

    job_id                                    skill_name
0   921716                              Marketing, Sales
1  1218575                          Health Care Provider
2  1829192                          Health Care Provider
3  2264355  Art/Creative, Design, Information Technology
4  9615617

In [ ]:
talent_profiles = (
    master_df
    .drop_duplicates(subset="job_id")
    .copy()
)

In [ ]:
talent_profiles.drop(
    columns=["skill_name", "skill_abr"],
    inplace=True
)

In [ ]:
talent_profiles = talent_profiles.merge(
    skills_grouped,
    on="job_id",
    how="left"
)

In [ ]:
print("Master DF :", master_df.shape)

print("Talent Profiles :", talent_profiles.shape)

Master DF : (280665, 15)
Talent Profiles : (123849, 14)

In [ ]:
talent_profiles.head()

,job_id,company_id,company_name,title,description,location,formatted_work_type,formatted_experience_level,skills_desc,company_name_full,company_description,industry_id,industry_name,skill_name
0,921716,2774458.0,Corcoran Sawyer Smith,Marketing Coordinator,Job descriptionA leading real estate firm in N...,"Princeton, NJ",Full-time,,Requirements: \n\nWe are seeking a College or ...,Corcoran Sawyer Smith,With years of experience helping local buyers ...,44.0,Real Estate,"Marketing, Sales"
1,1829192,NaN,NaN,Mental Health Therapist/Counselor,"At Aspen Therapy and Wellness , we are committ...","Fort Collins, CO",Full-time,,,NaN,NaN,NaN,NaN,Health Care Provider
2,10998357,64896719.0,The National Exemplar,Assitant Restaurant Manager,The National Exemplar is accepting application...,"Cincinnati, OH",Full-time,,We are currently accepting resumes for FOH - A...,The National Exemplar,"In April of 1983, The National Exemplar began ...",32.0,Restaurants,"Management, Manufacturing"
3,23221523,766262.0,"Abrams Fensterman, LLP",Senior Elder Law / Trusts and Estates Associat...,Senior Associate Attorney - Elder Law / Trusts...,"New Hyde Park, NY",Full-time,,This position requires a baseline understandin...,"Abrams Fensterman, LLP","Abrams Fensterman, LLP is a full-service law f...",9.0,Law Practice,Other
4,35982263,NaN,NaN,Service Technician,Looking for HVAC service tech with experience ...,"Burlington, IA",Full-time,,,NaN,NaN,122.0,Facilities Services,Information Technology

In [ ]:
talent_profiles["combined_text"] = (
    talent_profiles["title"].fillna("") + " " +
    talent_profiles["skill_name"].fillna("") + " " +
    talent_profiles["industry_name"].fillna("") + " " +
    talent_profiles["description"].fillna("") + " " +
    talent_profiles["company_description"].fillna("") + " " +
    talent_profiles["formatted_experience_level"].fillna("")
)

In [ ]:
talent_profiles.shape

(123849, 14)

In [ ]:
talent_profiles[["job_id", "title", "skill_name"]].head(10)

,job_id,title,skill_name
0,921716,Marketing Coordinator,"Marketing, Sales"
1,1829192,Mental Health Therapist/Counselor,Health Care Provider
2,10998357,Assitant Restaurant Manager,"Management, Manufacturing"
3,23221523,Senior Elder Law / Trusts and Estates Associat...,Other
4,35982263,Service Technician,Information Technology
5,91700727,Economic Development and Planning Intern,Project Management
6,103254301,Producer,"Art/Creative, Design, Information Technology"
7,112576855,Building Engineer,"Management, Manufacturing"
8,1218575,Respiratory Therapist,Health Care Provider
9,2264355,Worship Leader,"Art/Creative, Design, Information Technology"

In [ ]:
talent_profiles.isnull().sum().sort_values(ascending=False)

company_description           2762
company_name_full             1719
company_name                  1719
company_id                    1717
industry_name                 1536
industry_id                   1436
job_id                           0
formatted_work_type              0
location                         0
description                      0
title                            0
formatted_experience_level       0
skills_desc                      0
skill_name                       0
combined_text                    0
dtype: int64

In [ ]:
text_columns = [
    "title",
    "company_name",
    "company_name_full",
    "company_description",
    "description",
    "industry_name",
    "location",
    "formatted_work_type",
    "formatted_experience_level",
    "skill_name"
]

for col in text_columns:
    if col in talent_profiles.columns:
        talent_profiles[col] = talent_profiles[col].fillna("")

In [ ]:
talent_profiles["combined_text"] = (

    talent_profiles["title"] + " " +

    talent_profiles["skill_name"] + " " +

    talent_profiles["industry_name"] + " " +

    talent_profiles["description"] + " " +

    talent_profiles["company_description"] + " " +

    talent_profiles["formatted_experience_level"] + " " +

    talent_profiles["formatted_work_type"]

)

In [ ]:
talent_profiles[[
    "title",
    "skill_name",
    "industry_name",
    "combined_text"
]].head()

,title,skill_name,industry_name,combined_text
0,Marketing Coordinator,"Marketing, Sales",Real Estate,"Marketing Coordinator Marketing, Sales Real Es..."
1,Mental Health Therapist/Counselor,Health Care Provider,,Mental Health Therapist/Counselor Health Care ...
2,Assitant Restaurant Manager,"Management, Manufacturing",Restaurants,"Assitant Restaurant Manager Management, Manufa..."
3,Senior Elder Law / Trusts and Estates Associat...,Other,Law Practice,Senior Elder Law / Trusts and Estates Associat...
4,Service Technician,Information Technology,Facilities Services,Service Technician Information Technology Fac...

In [ ]:
import nltk

nltk.download("punkt")
nltk.download("punkt_tab")
nltk.download("stopwords")
nltk.download("wordnet")
nltk.download("omw-1.4")

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...

True

In [ ]:
import re
from sklearn.feature_extraction.text import ENGLISH_STOP_WORDS

stop_words = ENGLISH_STOP_WORDS

def clean_text(text):
    # Convert to string
    text = str(text).lower()

    # Remove HTML
    text = re.sub(r"<.*?>", " ", text)

    # Remove URLs
    text = re.sub(r"http\S+|www\S+", " ", text)

    # Keep only letters
    text = re.sub(r"[^a-zA-Z\s]", " ", text)

    # Remove extra spaces
    text = re.sub(r"\s+", " ", text).strip()

    # Remove stopwords
    words = [
        word for word in text.split()
        if word not in stop_words
    ]

    return " ".join(words)

In [ ]:
talent_profiles["clean_text"] = talent_profiles["combined_text"].apply(clean_text)

In [ ]:

from sklearn.feature_extraction.text import TfidfVectorizer

from sklearn.metrics.pairwise import cosine_similarity

import numpy as np

In [ ]:
vectorizer = TfidfVectorizer(
    max_features=10000,
    ngram_range=(1,2)
)

tfidf_matrix = vectorizer.fit_transform(
    talent_profiles["clean_text"]
)

print(tfidf_matrix.shape)

(123849, 10000)

In [ ]:
def recommend_talent(query, top_n=10):

    # Clean query
    query = clean_text(query)

    # Convert query into TF-IDF vector
    query_vector = vectorizer.transform([query])

    # Calculate similarity
    similarity = cosine_similarity(
        query_vector,
        tfidf_matrix
    ).flatten()

    # Top matching indices
    top_indices = similarity.argsort()[-top_n:][::-1]

    # Create result dataframe
    results = talent_profiles.iloc[top_indices].copy()

    results["Similarity Score"] = similarity[top_indices]

    return results[
        [
            "title",
            "company_name",
            "industry_name",
            "skill_name",
            "formatted_experience_level",
            "location",
            "Similarity Score"
        ]
    ]

In [ ]:
recommend_talent(
    "Need a motion graphics designer for real estate"
)

,title,company_name,industry_name,skill_name,formatted_experience_level,location,Similarity Score
26665,Real Estate Broker,AMR Real Estate,Real Estate,,,"Indianapolis, IN",0.519919
86055,Real Estate Agent,MBC Real Estate LLC,Real Estate,"Management, Sales",,"Detroit, MI",0.514435
78670,Real Estate Agent - Multifamily specialist,Dynamic Real Estate Assistance & Management,Real Estate,"Management, Sales",,Miami-Fort Lauderdale Area,0.502514
78288,Real Estate Credit Associate/VP,Selby Jennings,Real Estate,Finance,Associate,"Miami, FL",0.485316
70932,Real Estate Salesperson,METCAFE LIMITED,,"Management, Sales",,United States,0.479965
2052,Real Estate Attorney,Real Capital Solutions,Real Estate,"Finance, Legal",Associate,"Louisville, CO",0.476450
6168,Investment Real Estate Associate,Aurumys,Financial Services,"Finance, Sales",,"Denver, CO",0.475554
69599,Licensed Real Estate Agent,Heller The Home Seller - Heller Real Estate Group,Real Estate,"Management, Sales",,"San Diego, CA",0.474717
338,Real Estate Sales Agent,The Moorhead Team,Real Estate,"Management, Sales",,"Austin, Texas Metropolitan Area",0.469927
24406,Real Estate Administrative Assistant,New Energy Equity,Services for Renewable Energy,Administrative,Entry level,"Annapolis, MD",0.467496

In [ ]:
recommend_talent(
    "Need a UI UX designer"
)

,title,company_name,industry_name,skill_name,formatted_experience_level,location,Similarity Score
43154,UI/UX Designer,Sparkle Dryclean,Consumer Services,Customer Service,,"California, United States",0.615374
80352,UX Designer,SolidProfessor,E-Learning Providers,"Art/Creative, Design, Information Technology",Mid-Senior level,"Reno, NV",0.561497
48567,UI DESIGNER,Alrek Business Solutions Inc,Insurance,Information Technology,Mid-Senior level,"Louisville, KY",0.538081
24041,Senior UI/UX Developer/Designer,Clarity Security,IT Services and IT Consulting,,,United States,0.531780
41180,UI/UX Designer,Straight Arrow News,Broadcast Media Production and Distribution,"Art/Creative, Design",Associate,United States,0.513637
32446,User Experience Designer,Crescens Inc.,Government Administration,Design,Mid-Senior level,"Raleigh, NC",0.507548
46750,UX/UI Designer,MIDIScale,Education,"Art/Creative, Design, Information Technology",,United States,0.496130
33122,UX/UI Visual Designer,Conoscera Foundation,Non-profit Organizations,"Art/Creative, Design, Information Technology",,United States,0.481789
61776,Visual Designer,NK Interactive,Design,"Art/Creative, Design, Information Technology",,United States,0.474778
24050,Sr. UI/UX Designer,Calance,Wellness and Fitness Services,"Design, Information Technology",Mid-Senior level,"Irving, TX",0.470658

In [ ]:
def display_recommendations(query):

    results = recommend_talent(query)

    print("=" * 80)
    print(f"Query: {query}")
    print("=" * 80)

    for idx, (_, row) in enumerate(results.iterrows(), start=1):

        print(f"\n🏆 Rank {idx}")

        print(f"Title : {row['title']}")

        print(f"Company : {row['company_name']}")

        print(f"Industry : {row['industry_name']}")

        print(f"Skills : {row['skill_name']}")

        print(f"Experience : {row['formatted_experience_level']}")

        print(f"Location : {row['location']}")

        print(f"Similarity : {row['Similarity Score']:.3f}")

In [ ]:
display_recommendations(
    "Need someone who creates luxury real estate reels using motion graphics"
)

================================================================================
Query: Need someone who creates luxury real estate reels using motion graphics
================================================================================

🏆 Rank 1
Title : Real Estate Agent
Company : Luxury Realty Group LLC
Industry : Real Estate
Skills : Management, Sales
Experience :
Location : Las Vegas, NV
Similarity : 0.532

🏆 Rank 2
Title : Real Estate Agent
Company : Chase International
Industry : Real Estate
Skills : Management, Sales
Experience :
Location : Reno, NV
Similarity : 0.506

🏆 Rank 3
Title : Real Estate Broker
Company : AMR Real Estate
Industry : Real Estate
Skills :
Experience :
Location : Indianapolis, IN
Similarity : 0.496

🏆 Rank 4
Title : Real Estate Agent
Company : MBC Real Estate LLC
Industry : Real Estate
Skills : Management, Sales
Experience :
Location : Detroit, MI
Similarity : 0.485

🏆 Rank 5
Title : Real Estate Agent - Multifamily specialist
Company : Dynamic Real Estate Assistance & Management
Industry : Real Estate
Skills : Management, Sales
Experience :
Location : Miami-Fort Lauderdale Area
Similarity : 0.470

🏆 Rank 6
Title : Real Estate Credit Associate/VP
Company : Selby Jennings
Industry : Real Estate
Skills : Finance
Experience : Associate
Location : Miami, FL
Similarity : 0.453

🏆 Rank 7
Title : Real Estate Salesperson
Company : METCAFE LIMITED
Industry :
Skills : Management, Sales
Experience :
Location : United States
Similarity : 0.448

🏆 Rank 8
Title : Real Estate Attorney
Company : Real Capital Solutions
Industry : Real Estate
Skills : Finance, Legal
Experience : Associate
Location : Louisville, CO
Similarity : 0.445

🏆 Rank 9
Title : Investment Real Estate Associate
Company : Aurumys
Industry : Financial Services
Skills : Finance, Sales
Experience :
Location : Denver, CO
Similarity : 0.444

🏆 Rank 10
Title : Licensed Real Estate Agent
Company : Heller The Home Seller - Heller Real Estate Group
Industry : Real Estate
Skills : Management, Sales
Experience :
Location : San Diego, CA
Similarity : 0.444

In [ ]:
display_recommendations("Need a Python Data Analyst")

display_recommendations("Need a UI UX Designer")

display_recommendations("Need a Motion Graphics Designer")

display_recommendations("Need a Real Estate Marketing Expert")

display_recommendations("Need a Machine Learning Engineer")

================================================================================
Query: Need a Python Data Analyst
================================================================================

🏆 Rank 1
Title : Data Analyst
Company :
Industry :
Skills : Information Technology
Experience :
Location : Etna, OH
Similarity : 0.536

🏆 Rank 2
Title : Senior Data Analyst
Company : Stanley David and Associates
Industry : IT Services and IT Consulting
Skills : Information Technology
Experience :
Location : Charlotte, NC
Similarity : 0.494

🏆 Rank 3
Title : Data Analyst
Company : HRUCKUS
Industry : Government Relations Services
Skills : Information Technology
Experience : Mid-Senior level
Location : Washington, DC
Similarity : 0.470

🏆 Rank 4
Title : Credit Risk Analyst
Company : Piper Companies
Industry : Staffing and Recruiting
Skills : Finance, Sales
Experience : Mid-Senior level
Location : McLean, VA
Similarity : 0.466

🏆 Rank 5
Title : Business Data Analyst
Company : Piper Companies
Industry : Staffing and Recruiting
Skills : Information Technology
Experience : Mid-Senior level
Location : McLean, VA
Similarity : 0.453

🏆 Rank 6
Title : Data Analyst
Company : Aquarius Professional Staffing
Industry : Insurance
Skills : Analyst, Information Technology, Research
Experience : Mid-Senior level
Location : Indianapolis, IN
Similarity : 0.447

🏆 Rank 7
Title : Data Analyst
Company : DATAMETRICS SOFTWARE SYSTEMS INC.
Industry : IT Services and IT Consulting
Skills : Information Technology
Experience :
Location : Newark, NJ
Similarity : 0.430

🏆 Rank 8
Title : Data Analyst II/III
Company : University of Mississippi
Industry : Higher Education
Skills : Information Technology
Experience : Mid-Senior level
Location : University, MS
Similarity : 0.424

🏆 Rank 9
Title : Sr. Data Analyst
Company : INSPYR Solutions
Industry : Staffing and Recruiting
Skills : Information Technology
Experience : Mid-Senior level
Location : Deerfield Beach, FL
Similarity : 0.421

🏆 Rank 10
Title : Data Analyst (Only W2)
Company : Systellar Technologies
Industry : IT Services and IT Consulting
Skills : Information Technology
Experience :
Location : Juno Beach, FL
Similarity : 0.397
================================================================================
Query: Need a UI UX Designer
================================================================================

🏆 Rank 1
Title : UI/UX Designer
Company : Sparkle Dryclean
Industry : Consumer Services
Skills : Customer Service
Experience :
Location : California, United States
Similarity : 0.615

🏆 Rank 2
Title : UX Designer
Company : SolidProfessor
Industry : E-Learning Providers
Skills : Art/Creative, Design, Information Technology
Experience : Mid-Senior level
Location : Reno, NV
Similarity : 0.561

🏆 Rank 3
Title : UI DESIGNER
Company : Alrek Business Solutions Inc
Industry : Insurance
Skills : Information Technology
Experience : Mid-Senior level
Location : Louisville, KY
Similarity : 0.538

🏆 Rank 4
Title : Senior UI/UX Developer/Designer
Company : Clarity Security
Industry : IT Services and IT Consulting
Skills :
Experience :
Location : United States
Similarity : 0.532

🏆 Rank 5
Title : UI/UX Designer
Company : Straight Arrow News
Industry : Broadcast Media Production and Distribution
Skills : Art/Creative, Design
Experience : Associate
Location : United States
Similarity : 0.514

🏆 Rank 6
Title : User Experience Designer
Company : Crescens Inc.
Industry : Government Administration
Skills : Design
Experience : Mid-Senior level
Location : Raleigh, NC
Similarity : 0.508

🏆 Rank 7
Title : UX/UI Designer
Company : MIDIScale
Industry : Education
Skills : Art/Creative, Design, Information Technology
Experience :
Location : United States
Similarity : 0.496

🏆 Rank 8
Title : UX/UI Visual Designer
Company : Conoscera Foundation
Industry : Non-profit Organizations
Skills : Art/Creative, Design, Information Technology
Experience :
Location : United States
Similarity : 0.482

🏆 Rank 9
Title : Visual Designer
Company : NK Interactive
Industry : Design
Skills : Art/Creative, Design, Information Technology
Experience :
Location : United States
Similarity : 0.475

🏆 Rank 10
Title : Sr. UI/UX Designer
Company : Calance
Industry : Wellness and Fitness Services
Skills : Design, Information Technology
Experience : Mid-Senior level
Location : Irving, TX
Similarity : 0.471
================================================================================
Query: Need a Motion Graphics Designer
================================================================================

🏆 Rank 1
Title : Animator / Motion Graphics Designer - CPG / Retail
Company : Creative Circle
Industry : Staffing and Recruiting
Skills : Art/Creative, Design, Information Technology
Experience :
Location : Deerfield, MA
Similarity : 0.551

🏆 Rank 2
Title : Junior Motion Designer
Company : 22Squared
Industry : Advertising Services
Skills : Art/Creative, Design, Information Technology
Experience : Entry level
Location : Atlanta, GA
Similarity : 0.531

🏆 Rank 3
Title : Art Director
Company : Quad
Industry : Advertising Services
Skills : Art/Creative, Design, Information Technology
Experience : Associate
Location : United States
Similarity : 0.468

🏆 Rank 4
Title : Sr. Motion Designer
Company : Ginger Labs
Industry : Software Development
Skills : Art/Creative, Design, Information Technology
Experience :
Location : San Francisco, CA
Similarity : 0.448

🏆 Rank 5
Title : Motion Graphic Designer and Film Editor
Company : Elica Electric Co
Industry : Appliances, Electrical, and Electronics Manufacturing
Skills : Art/Creative, Design, Information Technology
Experience :
Location : New York, NY
Similarity : 0.441

🏆 Rank 6
Title : Sr Digital Graphic Designer
Company : The Betesh Group
Industry : Manufacturing
Skills :
Experience :
Location : Newark, NJ
Similarity : 0.439

🏆 Rank 7
Title : Motion Designer
Company : Motion Recruitment
Industry : Broadcast Media Production and Distribution
Skills : Design
Experience : Mid-Senior level
Location : New York, NY
Similarity : 0.422

🏆 Rank 8
Title : Animator
Company : On Camera Image Consulting
Industry : Professional Training and Coaching
Skills : Art/Creative, Design, Information Technology
Experience :
Location : United States
Similarity : 0.409

🏆 Rank 9
Title : Motion Graphics Designer
Company : Syndicatebleu
Industry : Staffing and Recruiting
Skills : Design
Experience : Associate
Location : Brooklyn, NY
Similarity : 0.378

🏆 Rank 10
Title : Freelance Motion Graphic Designer
Company : Vallure Agency
Industry : Advertising Services
Skills : Art/Creative, Design, Information Technology
Experience :
Location : Houston, TX
Similarity : 0.365
================================================================================
Query: Need a Real Estate Marketing Expert
================================================================================

🏆 Rank 1
Title : Real Estate Broker
Company : AMR Real Estate
Industry : Real Estate
Skills :
Experience :
Location : Indianapolis, IN
Similarity : 0.740

🏆 Rank 2
Title : Real Estate Agent
Company : MBC Real Estate LLC
Industry : Real Estate
Skills : Management, Sales
Experience :
Location : Detroit, MI
Similarity : 0.732

🏆 Rank 3
Title : Real Estate Agent - Multifamily specialist
Company : Dynamic Real Estate Assistance & Management
Industry : Real Estate
Skills : Management, Sales
Experience :
Location : Miami-Fort Lauderdale Area
Similarity : 0.715

🏆 Rank 4
Title : Real Estate Credit Associate/VP
Company : Selby Jennings
Industry : Real Estate
Skills : Finance
Experience : Associate
Location : Miami, FL
Similarity : 0.690

🏆 Rank 5
Title : Investment Real Estate Associate
Company : Aurumys
Industry : Financial Services
Skills : Finance, Sales
Experience :
Location : Denver, CO
Similarity : 0.687

🏆 Rank 6
Title : Real Estate Salesperson
Company : METCAFE LIMITED
Industry :
Skills : Management, Sales
Experience :
Location : United States
Similarity : 0.683

🏆 Rank 7
Title : Real Estate Attorney
Company : Real Capital Solutions
Industry : Real Estate
Skills : Finance, Legal
Experience : Associate
Location : Louisville, CO
Similarity : 0.678

🏆 Rank 8
Title : Real Estate Marketing Assistant
Company : Willard Jones Real Estate
Industry : Real Estate
Skills : Marketing, Sales
Experience :
Location : Chicago, IL
Similarity : 0.676

🏆 Rank 9
Title : Licensed Real Estate Agent
Company : Heller The Home Seller - Heller Real Estate Group
Industry : Real Estate
Skills : Management, Sales
Experience :
Location : San Diego, CA
Similarity : 0.675

🏆 Rank 10
Title : Real Estate Sales Agent
Company : The Moorhead Team
Industry : Real Estate
Skills : Management, Sales
Experience :
Location : Austin, Texas Metropolitan Area
Similarity : 0.668
================================================================================
Query: Need a Machine Learning Engineer
================================================================================

🏆 Rank 1
Title : Senior Machine Learning Engineer
Company : Commit: AI Career Agents for Developers
Industry : Technology, Information and Media
Skills : Engineering
Experience : Mid-Senior level
Location : United States
Similarity : 0.760

🏆 Rank 2
Title : Lead Machine Learning Engineer
Company : Confidential Jobs
Industry : Software Development
Skills : Engineering, Information Technology
Experience : Mid-Senior level
Location : United States
Similarity : 0.706

🏆 Rank 3
Title : Machine Learning Engineer - Remote
Company : Orbit Recruitment Group
Industry : Information Services
Skills : Information Technology
Experience : Mid-Senior level
Location : Austin, TX
Similarity : 0.702

🏆 Rank 4
Title : Machine Learning Engineer - Remote
Company : Orbit Recruitment Group
Industry : Information Services
Skills : Information Technology
Experience : Mid-Senior level
Location : Chicago, IL
Similarity : 0.702

🏆 Rank 5
Title : Machine Learning Engineer - Remote
Company : Orbit Recruitment Group
Industry : Information Services
Skills : Information Technology
Experience : Mid-Senior level
Location : Los Angeles County, CA
Similarity : 0.702

🏆 Rank 6
Title : Applied Machine Learning Research Scientist
Company : Coactive AI
Industry : Software Development
Skills : Other
Experience : Mid-Senior level
Location : San Jose, CA
Similarity : 0.681

🏆 Rank 7
Title :  Sr GenAI / Machine Learning Engineer
Company : Deltek
Industry : Software Development
Skills : Engineering
Experience : Mid-Senior level
Location : United States
Similarity : 0.660

🏆 Rank 8
Title : Senior Machine Learning Engineer
Company :
Industry :
Skills : Engineering, Information Technology
Experience :
Location : San Francisco, CA
Similarity : 0.645

🏆 Rank 9
Title : Senior Back-End Software Engineer (Machine Learning Emphasis)
Company : Awardco
Industry : Software Development
Skills : Engineering
Experience : Mid-Senior level
Location : Lindon, UT
Similarity : 0.624

🏆 Rank 10
Title : Senior Machine Learning Scientist
Company : Salesforce
Industry : Software Development
Skills : Other
Experience :
Location : New York City Metropolitan Area
Similarity : 0.622

# Conclusion

TalentMatch AI successfully recommends relevant talent profiles using NLP.

Achievements:

✔ Cleaned and integrated 11 LinkedIn datasets

✔ Built a Talent Profile knowledge base

✔ Engineered textual features

✔ Applied TF-IDF vectorization

✔ Used Cosine Similarity for recommendation

Current Limitation:

The model relies on keyword similarity.

Future Improvements:

• Sentence Transformers
• FAISS
• Explainable AI
• Hybrid Ranking

In [ ]:
import joblib

# Save the TF-IDF vectorizer
joblib.dump(vectorizer, "tfidf_vectorizer.pkl")

# Save the Talent Profiles
joblib.dump(talent_profiles, "talent_profiles.pkl")

# Save the TF-IDF matrix
joblib.dump(tfidf_matrix, "tfidf_matrix.pkl")

print("All files saved successfully!")

All files saved successfully!